version: '3'

services:
  react:
    container_name: react
    image: 'upcoderk/react-image'
    build:
      context: Front_end
      dockerfile: dockerfile
    ports:
      - 3000:3000

  spring:
    container_name: spring
    image: 'upcoderk/myapp'
    build:
      context: Back
      dockerfile: dockerfile
    ports:
      - 8081:8081
